version: '3'

services:
  web:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./nginx:/etc/nginx/conf.d
      #- ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: example_db
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - ./app:/app
     # - ./app/package.json:/app/package.json
     # - /app/node_modules
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - "9000:9000"
    volumes:
      - ./api:/var/www/html
    depends_on:
      - db

volumes:
  postgres_data:

